POST http://localhost:3000/app/v1/admin/login
content-type: application/json

{
    "username": "admin", 
    "password": "admin@123"
}


###
POST http://localhost:3000/app/v1/airline
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbkAxMjMiLCJpYXQiOjE2NzIxNTk2NjksImV4cCI6MTY3MjI0NjA2OX0.n1gt_MVrw7BEQCB94nXjdnCndoq7kcJww8S1lWiiG-s

{
    "name": "new vistara"
}

###

GET http://localhost:3000/app/v1/flight/search
Content-Type: application/json

{ "date": "27/12/2022", "from_place": "delhi", "to_place": "pune", "round_trip": "yes"}